<a href="https://colab.research.google.com/github/clwilkinson7/Temp/blob/main/Assignment1_Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from google.colab import files
uploaded = files.upload()

Saving housePrice.csv to housePrice.csv

In [9]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import csv
from sklearn.preprocessing import PolynomialFeatures
import pandas as pd

In [10]:
data = pd.read_csv('housePrice.csv')
data

,Price,Sqr Ft,Longitude,Latitude,Lot Size,Beds,Bath,Year Built,Price Sqr Ft,Last Sold Year,Last Sold For,Address,City,State,Zipcode,Address Full
0,"$895,900","3,447 sqft",-112.081985,33.560055,"7,895 sqft",4.0,4.5,2019.0,$260/sqft,NaN,NaN,"630 W Echo Ln Phoenix, AZ 85021",Phoenix,AZ,85021.0,"630 W Echo Ln, Phoenix, AZ 85021"
1,"$247,000","1,767 sqft",-96.676250,32.829227,"7,877 sqft",3.0,2.0,1954.0,$140/sqft,NaN,NaN,"2367 Highwood Dr Dallas, TX 75228",Dallas,TX,75228.0,"2367 Highwood Dr, Dallas, TX 75228"
2,"$44,900","1,232 sqft",-78.825190,42.913000,"3,510 sqft",3.0,1.0,1900.0,$36/sqft,NaN,NaN,"30 Hurlock Ave Buffalo, NY 14211",Buffalo,NY,14211.0,"30 Hurlock Ave, Buffalo, NY 14211"
3,"$959,000","1,417 sqft",-73.860170,40.722960,"2,598 sqft",3.0,2.0,1939.0,$677/sqft,2009.0,"$532,000","6416 Alderton St Flushing, NY 11374",Flushing,NY,11374.0,"6416 Alderton St, Flushing, NY 11374"
4,"$83,500",440 sqft,-80.206314,25.937965,NaN,NaN,1.0,1971.0,$190/sqft,2007.0,"$52,000","251 NW 177th St #A-123 Miami Gardens, FL 33169",Miami Gardens,FL,33169.0,"251 NW 177th St #A-123, Miami Gardens, FL 33169"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30001,"$300,000",733 sqft,-80.187720,25.771372,NaN,1.0,1.0,2008.0,$409/sqft,2014.0,"$345,000","300 S Biscayne Blvd #T-3507 Miami, FL 33131",Miami,FL,33131.0,"300 S Biscayne Blvd #T-3507, Miami, FL 33131"
30002,"$119,000","1,716 sqft",-121.031560,37.680702,18.84 acres,3.0,2.0,1998.0,$69/sqft,NaN,NaN,"2621 Prescott Rd #161 Modesto, CA 95350",Modesto,CA,95350.0,"2621 Prescott Rd #161, Modesto, CA 95350"
30003,"$210,000",NaN,-91.137700,30.440481,8276 sqft,NaN,NaN,NaN,NaN,NaN,NaN,"17 Claycut Rd #A Baton Rouge, LA 70806",Baton Rouge,LA,70806.0,"17 Claycut Rd #A, Baton Rouge, LA 70806"
30004,"$329,000",NaN,-73.913930,40.699930,NaN,7.0,3.0,2007.0,NaN,NaN,NaN,"360 Grove St Brooklyn, NY 11237",Brooklyn,NY,11237.0,"360 Grove St, Brooklyn, NY 11237"
30005,"$4,500,000","10,149 sqft",-78.603240,35.934372,5.28 acres,4.0,9.0,2004.0,$443/sqft,2018.0,"$5,500,000","1624 Morning Mountain Rd Raleigh, NC 27614",Raleigh,NC,27614.0,"1624 Morning Mountain Rd, Raleigh, NC 27614"

In [12]:
issues = ["$", ",", "sqft", "acres", "acre", "/", ["+"]]
for col in data:
  for issue in issues:
    try:
      data[col] = data[col].str.replace(issue, "")
    except AttributeError:
      pass

In [13]:
for col in data:
  try:
    data[col] = data[col].astype(float)
  except ValueError:
    pass

In [14]:
data

,Price,Sqr Ft,Longitude,Latitude,Lot Size,Beds,Bath,Year Built,Price Sqr Ft,Last Sold Year,Last Sold For,Address,City,State,Zipcode,Address Full
0,NaN,NaN,-112.081985,33.560055,NaN,4.0,4.5,2019.0,NaN,NaN,NaN,NaN,NaN,NaN,85021.0,NaN
1,NaN,NaN,-96.676250,32.829227,NaN,3.0,2.0,1954.0,NaN,NaN,NaN,NaN,NaN,NaN,75228.0,NaN
2,NaN,NaN,-78.825190,42.913000,NaN,3.0,1.0,1900.0,NaN,NaN,NaN,NaN,NaN,NaN,14211.0,NaN
3,NaN,NaN,-73.860170,40.722960,NaN,3.0,2.0,1939.0,NaN,2009.0,NaN,NaN,NaN,NaN,11374.0,NaN
4,NaN,NaN,-80.206314,25.937965,NaN,NaN,1.0,1971.0,NaN,2007.0,NaN,NaN,NaN,NaN,33169.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30001,NaN,NaN,-80.187720,25.771372,NaN,1.0,1.0,2008.0,NaN,2014.0,NaN,NaN,NaN,NaN,33131.0,NaN
30002,NaN,NaN,-121.031560,37.680702,NaN,3.0,2.0,1998.0,NaN,NaN,NaN,NaN,NaN,NaN,95350.0,NaN
30003,NaN,NaN,-91.137700,30.440481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70806.0,NaN
30004,NaN,NaN,-73.913930,40.699930,NaN,7.0,3.0,2007.0,NaN,NaN,NaN,NaN,NaN,NaN,11237.0,NaN
30005,NaN,NaN,-78.603240,35.934372,NaN,4.0,9.0,2004.0,NaN,2018.0,NaN,NaN,NaN,NaN,27614.0,NaN

In [17]:
linReg = LinearRegression()
linReg.fit((data["Bath"], data["Price"])

plt.title(("Linear Regression\nScore = ",  linRegScore))
for i in range(len(data["Bath"])):
  plt.scatter(data["Bath"].iloc[i], data["Price"].iloc[i], c="blue", marker="o")

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
from sklearn.cluster import KMeans

inertia = []

for i in range(1, 25):
    kmeans = KMeans(n_clusters=i)
    kmeans.fit(newData["Bath"])
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 6))
plt.plot(range(1, 25), inertia, marker='o')
plt.title('Elbow Method for Optimal k')
plt.xlabel('Number of Clusters')
plt.ylabel('Inertia')
plt.show()